spring:
  application:
    name: grivet-service-discovery

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

server:
  port: 8761
  compression:
    enabled: true
    undertow:
      accesslog:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
