-- Tested w/ HSQLDB only

CREATE PROCEDURE GET_ATTRIBUTES_CREATED_BEFORE (IN createdTime TIMESTAMP)
  READS SQL DATA
  DYNAMIC RESULT SETS 1
  BEGIN ATOMIC
  	  DECLARE results SCROLL CURSOR WITH HOLD WITH RETURN FOR
	  SELECT NAME, CREATED_TIME FROM ATTRIBUTE WHERE UNIX_MILLIS(CREATED_TIME) < UNIX_MILLIS(createdTime);
	  OPEN results;
  END;