# API GATEWAY

# This file uses the version 3 docker-compose file format, described here:
# https://docs.docker.com/compose/compose-file/compose-file-v3/#compose-file-structure-and-examples

version: '3.8'

services:

  ### SPRING CLOUD GATEWAY
  spring-cloud-gateway:
    image: fastnsilver/grivet-api-gateway
    ports:
      - 80:9999
    extra_hosts:
      - "signoz:host-gateway"
    environment:
      - SPRING_APPLICATION_NAME=grivet-api-gateway
      - SPRING_PROFILES_ACTIVE=docker,insecure
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888
      - DOCKER_IP=$DOCKER_IP
      - JAVA_OPTS=-Xmx256m -XX:+UseG1GC -XX:+UseStringDeduplication
      - OTEL_RESOURCE_ATTRIBUTES=service.name=grivet-api-gateway
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://signoz:4317
