# API GATEWAY

# This file uses the version 2 docker-compose file format, described here:
# https://docs.docker.com/compose/compose-file/#version-2

version: '2'

services:

  ### SPRING CLOUD GATEWAY
  spring-cloud-gateway:
    image: fastnsilver/grivet-api-gateway
    ports:
      - 9999:9999
    environment:
      - DOCKER_IP=$DOCKER_IP
      - JAVA_OPTS=-Xmx256m -XX:+UseG1GC -XX:+UseStringDeduplication
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://discovery-service:8761/eureka/
