# DOCKER COMPOSE CONFIGURATION
# This file uses the version 3 docker-compose file format, described here:
# https://docs.docker.com/compose/compose-file/compose-file-v3/#compose-file-structure-and-examples

version: '3.8'

services:

  ## INFRASTRUCTURE SERVICES

  ### PROMETHEUS
  prometheus:
    image: prom/prometheus:v2.47.2
    ports:
      - 9090:9090

  ### GRAFANA
  grafana:
    image: grafana/grafana:10.2.0
    ports:
      - 3000:3000
    env_file:
      - ./monitoring/grafana.env
    links:
      - prometheus

  ### CADVISOR
  cadvisor:
    # @see https://github.com/google/cadvisor/issues/1943
    image: gcr.io/cadvisor/cadvisor:v0.46.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 9080:8080

  ### DATABASE
  db:
    image: mysql:8.1
    privileged: true
    ports:
      - 3306:3306
    env_file:
      - ./mysql/db.env
    volumes:
      - db-data:/var/lib/mysql

  ### DATABASE ADMINISTRATION
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    ports:
      - 8090:80
    env_file:
      - ./phpmyadmin/admin.env
    links:
      - db


  ## NEFLIX OSS, SUPPORT SERVICES

  ### CONFIGURATION MANAGEMENT
  config-service:
    image: fastnsilver/grivet-config-server
    ports:
      - 8888:8888
    extra_hosts:
      - "signoz:host-gateway"
    environment:
      - DOCKER_IP=$DOCKER_IP
      - JAVA_OPTS=-Xmx2g -XX:+UseG1GC -XX:+UseStringDeduplication
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - OTEL_RESOURCE_ATTRIBUTES=service.name=grivet-config-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://signoz:4317
      # Replace these with your own Git repository, username, personal access token, and branch!
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/fastnsilver/grivet-config-repo
      - SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME=fastnsilver
      - SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD=
      - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT-LABEL=main

  ### EUREKA, DISCOVERY
  discovery-service:
    image: fastnsilver/grivet-discovery-service
    ports:
      - 8761:8761
    extra_hosts:
      - "signoz:host-gateway"
    environment:
      - DOCKER_IP=$DOCKER_IP
      - JAVA_OPTS=-Xmx2g -XX:+UseG1GC -XX:+UseStringDeduplication
      - OTEL_RESOURCE_ATTRIBUTES=service.name=grivet-discovery-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://signoz:4317

  ## SPRING BOOT SERVICE ADMINISTRATION
  springboot-admin:
    image: fastnsilver/grivet-microservices-console
    ports:
      - 5555:5555
    extra_hosts:
      - "signoz:host-gateway"
    links:
      - discovery-service
    environment:
      - SPRING_APPLICATION_NAME=grivet-microservices-console
      - SPRING_PROFILES_ACTIVE=docker,insecure
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888
      - DOCKER_IP=$DOCKER_IP
      - JAVA_OPTS=-Xmx1g -XX:+UseG1GC -XX:+UseStringDeduplication
      - OTEL_RESOURCE_ATTRIBUTES=service.name=grivet-microservices-console
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://signoz:4317

volumes:
  db-data: