# DOCKER COMPOSE CONFIGURATION
# This file uses the version 2 docker-compose file format, described here:
# https://docs.docker.com/compose/compose-file/#version-2

version: '2'

services:

  ## INFRASTRUCTURE SERVICES
  
  ### PERSISTENT DATA VOLUME
  
  # On a Mac, execute 
  #    dscacheutil -q user | grep -A 3 -B 2 -e uid:\ 5'[0-9][0-9]'
  # in a Terminal instance to obtain the uid:gid for the account that runs your docker-machine instance
  # You will want to edit the command below if your uid:gid differ
  data:
    image: busybox
    command: "mkdir /data && chown 502:20 /data && chmod 700 /data"
  
  ### KIBANA
  kibana:
    image: kibana:latest
    links:
      - elasticsearch
    ports:
      - 5601:5601
      
  ### ELASTICSEARCH
  elasticsearch:
    image: elasticsearch:latest
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx4g
  
  ### REDIS
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
  
  ### LOGSTASH
  logstash:
    image: logstash:latest
    command: 'logstash -f /logstash.conf -v'
    volumes:
      - ./monitoring/logstash.conf:/logstash.conf
    links:
      - redis
      - elasticsearch
  
  ### LOGSPOUT
  
  # Thank you R. Toma 
  # (@see https://github.com/rtoma/logspout-redis-logstash/blob/master/example/docker-compose.yml)
  
  logspout:
    image: rtoma/logspout-redis-logstash
    command: 'redis://redis'
    environment:
      - DEBUG=true
      - REDIS_KEY=logstash
      - REDIS_DOCKER_HOST=redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    links:
      - redis
      
  ### PROMETHEUS
  prometheus:
    image: prom/prometheus:v2.47.2
    ports:
      - 9090:9090
  
  ### GRAFANA
  grafana:
    image: grafana/grafana:10.2.0
    ports:
      - 3000:3000
    env_file:
      - ./monitoring/grafana.env
    links:
      - prometheus
      
  ### CADVISOR
  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 9080:8080
      
  ### DATABASE
  db:
    image: mysql:8.2
    privileged: true
    ports:
      - 3306:3306
    env_file:
      - ./mysql/db.env
    volumes_from:
      - data
      
  ### DATABASE ADMINISTRATION
  phpmyadmin:
    image: phpmyadmin:latest
    ports: 
      - 4000:80
    env_file:
      - ./phpmyadmin/admin.env
    links:
      - db
      

  ## NEFLIX OSS, SUPPORT SERVICES
  
  ### CONFIGURATION MANAGEMENT
  config-service:
    image: fastnsilver/grivet-config-server
    ports:
      - 8888:8888
    environment:
      - DOCKER_IP=$DOCKER_IP
      - JAVA_OPTS=-Xmx2g -XX:+UseG1GC -XX:+UseStringDeduplication
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
  
  ### EUREKA, DISCOVERY
  discovery-service:
    image: fastnsilver/grivet-discovery-service
    ports:
      - 8761:8761
    environment:
      - DOCKER_IP=$DOCKER_IP
      - JAVA_OPTS=-Xmx2g -XX:+UseG1GC -XX:+UseStringDeduplication
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
  
  ### SPRING BOOT SERVICE ADMINISTRATION
#  springboot-admin:
#    image: fastnsilver/grivet-boot-admin
#    ports:
#      - 5555:5555
#    links:
#      - discovery-service
#    environment:
#      - DOCKER_IP=$DOCKER_IP
#      - JAVA_OPTS=-Xmx1g -XX:+UseG1GC -XX:+UseStringDeduplication
#      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
#      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
#      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
#      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://discovery-service:8761/eureka/
  
  ### SPRING BOOT DASHBOARD
  springboot-dashboard:
    image: fastnsilver/grivet-dashboard
    ports:
      - 8088:8088
    links:
      - discovery-service
      - redis
    environment:
      - DOCKER_IP=$DOCKER_IP
      - SPRING_REDIS_HOST=redis
      - JAVA_OPTS=-Xmx1g -XX:+UseG1GC -XX:+UseStringDeduplication
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_HEALTH_CHECK_ENABELD=false
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://discovery-service:8761/eureka/
