# Set a Personal Access Token for the username and leave password blank
# @see https://github.com/spring-cloud/spring-cloud-config/issues/55
# For private repo on Github, visit https://github.com/settings/tokens,
# then generate token with repo scope
# Remember to set the spring.cloud.config.server.git.username property value
# Other Git repo providers:
#   - Gitlab, https://docs.gitlab.com/ce/user/profile/personal_access_tokens.html
#   - Bitbucket, https://confluence.atlassian.com/bitbucketserver/personal-access-tokens-939515499.html
spring:
  application:
    name: grivet-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fastnsilver/grivet-config-repo.git
          password:

server:
  port: 8888
  compression:
    enabled: true
  undertow:
    accesslog:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
