spring:
  # (2017-10-02) As of Spring Cloud Finchley.M2+ certain auto-config and config don't work, so disable! 
  autoconfigure:
    exclude: 
      - org.springframework.cloud.netflix.hystrix.HystrixAutoConfiguration
      - org.springframework.cloud.stream.config.BindersHealthIndicatorAutoConfiguration
      - org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration

endpoints:
  default:
    web:
      enabled: true
