spring:
  application:
    name: microservices-console

server:
  port: 5555
  compression:
    enabled: true
  undertow:
    accesslog:
      enabled: true

ribbon:
  ServerListRefreshInterval: 1000

---

spring:
  config.activate.on-profile: docker

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
