/*
 * Copyright 2015 - Chris Phillipson
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.fns.grivet.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.validation.constraints.Size;

/**
 * A {@code Class} is akin to an abstract base {@link java.lang.Class} 
 * but is constrained to the definition of member variables. A {@code Class} 
 * may be linked to a <a href="http://json-schema.org/">JSON Schema</a> for purposes of
 * validating an object's attributes (expressed in JSON format).
 * @see ClassAttribute
 * 
 * @author Chris Phillipson
 */
@Entity
public class Class extends Audited {

    /** 
     * Version number used during deserialization to verify that the sender and receiver 
     * of this serialized object have loaded classes for this object that 
     * are compatible with respect to serialization. 
     */
    private static final long serialVersionUID = 1L;

    /** The id. Auto-generated by the underyling data-store. */
    @Id
    @GeneratedValue
    private Integer id;

    /** The name of the class. Must be non-null, unique and less than 256 characters. */
    @Size(max=255)
    @Column(nullable=false, unique=true)
    private String name;
    
    /** The description of the attribute. Optional, but must be less than equal to 1000 characters. */
    @Column
    private String description;
        
    /** Whether or not an object (JSON payload) should be validated before being persisted.  Default is false. */
    @Column
    private boolean validatable;
    
    /** A JSON Schema.  Used to validate an object (JSON payload). */
    @Column
    private String jsonSchema;

    /**
     * For internal use only! Instantiates a new class.
     */
    protected Class() {
    }
    
    /**
     * Instantiates a new attribute.
     *
     * @param name
     *            the name
     * @param description
     *            the description
     * @param user
     *            the currently authenticated principal
     */
    public Class(String name, String description, User user) {
        super(user);
        this.name = name;
        this.description = description;
    }
    
    /**
     * Gets the id.
     *
     * @return the id
     */
    public Integer getId() {
        return id;
    }
    
    /**
     * Gets the name.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }
    
    /**
     * Gets the description.
     *
     * @return the description
     */
    public String getDescription() {
        return description;
    }
    
    /**
     * Sets the description
     * 
     * @param description a description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Sets whether or not an object (JSON payload) should be validated
     * before being persisted.
     *
     * @param validatable
     *            true or false
     */
    public void setValidatable(boolean validatable) {
        this.validatable = validatable;
    }
    
    /**
     * @return whether or not an object (JSON payload) should be validated
     * before being persisted.
     */
    public boolean isValidatable() {
        return validatable;
    }
    
    /**
     * Gets the JSON Schema.
     *
     * @return the JSON Schema
     */
    public String getJsonSchema() {
        return jsonSchema;
    }

    /**
     * Sets the JSON Schema.
     *
     * @param jsonSchema
     *            a JSON Schema
     */
    public void setJsonSchema(String jsonSchema) {
        this.jsonSchema = jsonSchema;
    }
    
}
